In [6]:
print("Welcome to Machine Learning")

Welcome to Machine Learning


In [7]:
myint = 330775
print(myint)
myfloat = 3.1415
print(myfloat)
myFirstString = '330775'
print('myFirstString:', myFirstString)
mySecondString = "machine learning"
print('mySecondString: ', mySecondString)
addition = myint + myfloat
print('addition: ', addition)
subtraction = myint - myfloat
print('subtraction: ', subtraction)
multiplication = myint * myfloat
print('multiplication: ', multiplication)
division = myint / myfloat
print('division: ', division)
mod = myint % myfloat
print('mod:', mod)
	
concatenate1 = myFirstString + mySecondString
print('concatenate1: ', concatenate1)
myFirstString += mySecondString
print('myFirstString: ', myFirstString)
concatenate2 = str(myint) + mySecondString
print('concatenate2: ',concatenate2)


330775
3.1415
myFirstString: 330775
mySecondString:  machine learning
addition:  330778.1415
subtraction:  330771.8585
multiplication:  1039129.6625000001
division:  105292.0579341079
mod: 0.1819999999809223
concatenate1:  330775machine learning
myFirstString:  330775machine learning
concatenate2:  330775machine learning


In [8]:
intList = [330, 775]
stringList = []
stringList.append("machine")
stringList.append("learning")

print(intList[0])
print(intList[1])
print(stringList)


330
775
['machine', 'learning']


In [9]:
name = "John"
age = 23
print(name == "John")
print(age > 25)


True
False


In [10]:
for x in range(5):
    print(x)

for x in range(1, 5):
    print(x)

for x in stringList:
    print(x)


0
1
2
3
4
1
2
3
4
machine
learning


In [11]:
seq = ['one', 'two', 'three']
for i in range(len(seq)):
    print(i)
    print(seq[i])

seq = ['one', 'two', 'three']
for i, element in enumerate(seq):
    print(i)
    print(element)



0
one
1
two
2
three
0
one
1
two
2
three


In [12]:
def convert2letter(totalScore):
    if totalScore >= 90:
        return "A"
    elif totalScore >= 80:
        return "B"
    else:
        return "C"


johnScore = 80
print(convert2letter(johnScore))

name="Alice"
age=30
greeting=f'Hello, my name is {name} and I am {age} years old.'
print(greeting)

scoreBook={}
scoreBook["John"]=80
scoreBook["Jack"]=75
scoreBook["Jill"]=92

print(scoreBook)
# F-string with dictionary
print(f"Jack receives a {convert2letter(scoreBook['Jack'])} from machine learning.")


B
Hello, my name is Alice and I am 30 years old.
{'John': 80, 'Jack': 75, 'Jill': 92}
Jack receives a C from machine learning.


In [13]:
import numpy as np

a = np.zeros((3,4))
print(a)
print(a.ndim)
print(a.shape)
print(a.size)


np.linspace(1, 5, 9)

np.random.rand(3,4)
np.random.randn(3,4)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2
(3, 4)
12


array([[-0.21055919,  0.12739024, -0.13808682,  0.21394934],
       [ 0.61198126, -2.16688058, -0.42944024,  0.72774181],
       [-0.01094026, -0.7196291 ,  0.58753198, -1.03909256]])

### mean(): Calculates the average of array elements.
### max(): Finds the maximum value.
### min(): Finds the minimum value.
### sum(): Adds up all the elements.
### std(): Computes the standard deviation.
### var(): Computes the variance.

In [14]:
import numpy as np

homework = np.array([[1,2,3,4], [10, 20, 30, 40], [60, 70, 80, 90]])
print(homework)  

# Overall mean of the array
overall_mean = np.mean(homework)
print("Overall Mean:", overall_mean)

# Maximum value
max_value = np.max(homework)
print("Maximum:", max_value)

# Minimum value
min_value = np.min(homework)
print("Minimum:", min_value)

# Sum of all elements
sum_value = np.sum(homework)
print("Sum:", sum_value)

# Standard deviation
std_value = np.std(homework)
print("Standard Deviation:", std_value)

# Variance
var_value = np.var(homework)
print("Variance:", var_value)

[[ 1  2  3  4]
 [10 20 30 40]
 [60 70 80 90]]
Overall Mean: 34.166666666666664
Maximum: 90
Minimum: 1
Sum: 410
Standard Deviation: 31.651312066888405
Variance: 1001.8055555555557


In [15]:
import numpy as np

a = np.array([1, 2, 3, 4, 10, 20, 30])
print(a[3])
print(a[1:3])
print(a[1:5:2])
print(a[2:-1])
print(a[:2])


4
[2 3]
[2 4]
[ 3  4 10 20]
[1 2]


In [ ]:
import numpy as np

homework = np.array([[1,2,3,4], [10, 20, 30, 40], [60, 70, 80, 90]])

homework[(0,2), 1:3]

array([[ 1,  4],
       [10, 40],
       [60, 90]])

### Explanation: This indexing method selects rows at index 0 and 2 and columns from index 1 to 3 (excluding 3).
